### ISSUE TITLE
Is there a way to control how Date objects are translated?

### ISSUE THREAD

**Issue by renkun-ken** [viking/r-yaml#18]
``` rconsole
> yaml::as.yaml(list(date = as.Date("2012-10-10")))
[1] "date: 15623.0\n"
```

If there's a handler for `Date`, `POSIXct`, and `POSIXlt` objects, one should be able to produce the correct date string.

Would it be possible for `yaml::as.yaml()` support such an argument?

**Comment by viking** [comment]
This is supported now in the development version of this package. See the 'handlers' section of the README for more information: https://github.com/viking/r-yaml#handlers-1
