### ISSUE TITLE
Make package devtools compatible

### ISSUE THREAD

**Issue by airstrike** [viking/r-yaml#26]
Any chance we could have this be compatible with [hadley/devtools](https://github.com/hadley/devtools) so that we can use `devtools::install_github("viking/r-yaml")` to install from source?

**Comment by yihui** [comment]
👍 I have to confess, as an R package developer for almost 10 years, that I spent more than two hours on figuring out how to install this package on Windows (I was only using Windows for testing purposes). At least I don't see the significant value of using brew. Then `re2c`, the use of `R --vanilla` (meaning packages installed to `R_LIBS_USER` are not available), and just way too much pain to figure out all these details.

**Comment by hadley** [comment]
Even the install instructions in the readme are incorrect. It would be great if we could make this package easier to install. I'd be happy to help out.

**Comment by viking** [comment]
I'll consider it.

**Comment by viking** [comment]
Fixing the README is obviously something that I agree should be done. Storing the output of `re2c` in the repository doesn't seem like a big deal, either, if it makes things easier.

**Comment by QuLogic** [comment]
On a related note, it would nice if it would be possible to build against system `libyaml`, for those of us who make distro packages (though I see there might be some patches to `libyaml`.)

**Comment by viking** [comment]
@QuLogic You are correct, there are some patches to LibYAML in the R package.

**Comment by viking** [comment]
This should be fixed now. Enjoy.
