### ISSUE TITLE
Support for big integers (bit64), please?

### ISSUE THREAD

**Issue by adamryczkowski** [viking/r-yaml#29]
I'd love to store object sizes in yaml metadata files I use. Unfortunately object sizes I deal with often exceed 2GB, so I cannot store them as integer. I approximate them with floating point numbers, but the correct and efficient solution would be to use 64bit integers in yaml. 

Can I kindly ask to support them? :smiley:

**Comment by viking** [comment]
Unfortunately, this is a limitation in R, not in the YAML package for R.

**Comment by viking** [comment]
R does not natively support 64-bit integers, so the only way to store large numbers is to use numeric. See `help(integer)` for more information.
