### ISSUE TITLE
as.yaml logicals: TRUE/FALSE instead of yes/no in output string

### ISSUE THREAD

**Issue by wlandau** [viking/r-yaml#30]
I would really like to be able to use `as.yaml` in a way that outputs TRUE/FALSE instead of yes/no for logicals. Currently, I'm running into [this issue](https://github.com/richfitz/remake/issues/88) with [`remake`](https://github.com/richfitz/remake) and [`parallelRemake`](https://github.com/wlandau/parallelRemake). Maybe it would be possible to add another argument to `as.yaml` to select TRUE/FALSE, which could then be passed down to `R_format_logical` in `src/r-ext.c`.

**Comment by krlmlr** [comment]
Have you seen https://github.com/viking/r-yaml/issues/5#issuecomment-16464325?

**Comment by wlandau** [comment]
@krlmlr Thanks for the pointer, I did not know this before.

**Comment by viking** [comment]
There's currently no way to control how `as.yaml` converts logical vectors, but I agree that it would be a nice feature. I will work on it.

**Comment by wlandau** [comment]
Thanks!

**Comment by viking** [comment]
This is supported now in the development version of this package. See the 'handlers' section of the README for more information: https://github.com/viking/r-yaml#handlers-1
