### ISSUE TITLE
Include file name in errors

### ISSUE THREAD

**Issue by hadley** [viking/r-yaml#34]
I'm often calling `yaml.load` in a loop, so it would be useful to include the file name in the error as this isn't very informative:

```R
Error in yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\n"),  : 
  Scanner error: while scanning a simple key at line 7, column 1could not find expected ':' at line 8, column 51
```

**Comment by hadley** [comment]
(Also note the missing space, and it would be better to not include the call)

**Comment by viking** [comment]
Do you mean `yaml.load_file`? That error message indicates the call was likely made from `yaml.load_file`.

**Comment by viking** [comment]
I am working on adding a new argument to `yaml.load` for prepending a label to error messages. The label will be auto-populated from `yaml.load_file` by either using the specified filename or the description of the supplied connection object.

**Comment by hadley** [comment]
Yeah, `yaml.load_file()`

**Comment by viking** [comment]
The new functionality is implemented in the following commits:
- https://github.com/viking/r-yaml/commit/712f61e77bc30964530ec997f78983d6c12bb80d
- https://github.com/viking/r-yaml/commit/95df3986f75aa3afa7b36bb6c475f6e12fb63bd2
- https://github.com/viking/r-yaml/commit/440bcdc792be8ac4fb47d9dccb039c131439184f
