### ISSUE TITLE
Segmentation fault when compiling with -std=c11

### ISSUE THREAD

**Issue by viking** [viking/r-yaml#35]
I have noticed a segmentation fault when using your "yaml" package when 
it is compiled with "-std=c11", along with quite a few compiler 
warnings. While this may be an uncommon setting now, it could become 
standard eventually.

Steps to reproduce:

- Create a directory ~/.R and there a file Makevars with the following 
contents:

PKG_CFLAGS:=$(PKG_CFLAGS) -Wall -pedantic -std=c11

- Install yaml 2.1.14 from CRAN

- Run in the shell:

R -q -e 'yaml::yaml.load("test:")'

Output:

  *** caught segfault ***
address 0xffffffff90b5d620, cause 'memory not mapped'

Traceback:
  1: .Call("yaml.load", enc2utf8(string), as.named.list, handlers,     
PACKAGE = "yaml")
  2: yaml::yaml.load("test:")

I'm on Ubuntu 16.10 with R 3.3.3 from CRAN's Debian repository.

**Comment by eddelbuettel** [comment]
I cannot replicate this:
- Ubuntu 17.04, 
- default g++ is 6.3 which defaults to C++11. 

It passes
- "as is"
- with `CXX_STD = CXX11` added to  `src/Makevars`

**Comment by viking** [comment]
I also can't reproduce this. Please reopen if this is still an issue.
