### ISSUE TITLE
change `readLines(input, encoding = "UTF-8")` to `readr::read_lines(input)` in `yaml.load_file()`

### ISSUE THREAD

**Issue by gitzhuoer** [viking/r-yaml#38]
report a bug @viking 

download [*_bookdown.yaml*](https://raw.githubusercontent.com/yihui/r-ninja/master/_bookdown.yml)

```R
yaml::yaml.load_file('_bookdown.yml')
```

```
Error in yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\n"),  : 
  Reader error: invalid leading UTF-8 octet: #B5 at 39
```

**Comment by gitzhuoer** [comment]
```R
debug(yaml::yaml.load_file)
yaml::yaml.load_file('_bookdown.yml')
```

```
debugging in: yaml::yaml.load_file("_bookdown.yml")
debug: {
    yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\\n"), 
        ...)
}
Browse[2]> readLines(input, encoding = "UTF-8")
[1] "book_filename: r-ninja"                  "chapter_name: [\"�\xda\", \"\xd5\xc2\"]"
[3] "repo: https://github.com/yihui/r-ninja/" "output_dir: _book"                      
[5] "clean: [packages.bib, r-ninja.bbl]"     
Browse[2]> readr::read_lines(input)
[1] "book_filename: r-ninja"                  "chapter_name: [\"第\", \"章\"]"         
[3] "repo: https://github.com/yihui/r-ninja/" "output_dir: _book"                      
[5] "clean: [packages.bib, r-ninja.bbl]" 
```

**Comment by gitzhuoer** [comment]
I find the reason: I set `options(encoding = "UTF-8")`.

I use Windows 10 Chinese edition. When I let `encoding` to be the default value, `"native.enc"`, everything works well.

But I think user should have the right to.

Maybe you can change to `readr::read_lines`. If you don't want to depend on **readr**, you can add a judgement statement. When `encoding` is set to `"UTF-8"`, you needn't to add `encoding = "UTF-8"` in `readLines(input)`.

Anyway, I just give an advise. I hope when someone encounter the same problem, he/she may find this page.

**Comment by gitzhuoer** [comment]
Anyway, I just give an advise. You make the decision. 

I hope when someone encounter the same problem, he/she may find this page. Then the hour I spent for this issue wasn't wasted.

**Comment by viking** [comment]
Thanks for reaching out and looking into this issue.

I'm not keen on adding a dependency to the YAML package unless there is a compelling reason to do so. If there is a way to use the base functions for improved unicode support, then I'd rather go that route. However, if using the readr package is the best way to accomplish that, it makes sense to use it.

I'm hoping to devote some time to work through the current YAML issues soon. I will get back to you.

**Comment by gitzhuoer** [comment]
Maybe I find a solution.

use `file(input, encoding = "UTF-8")` instead of `input`.

I will explain it soon.

**Comment by gitzhuoer** [comment]
Maybe I find a solution.

use `file(input, encoding = "UTF-8")` instead of `input`.

I will explain it soon.

**Comment by gitzhuoer** [comment]
First of all, in `?readLines`, for parameter `encoding`

> It is used to mark character strings as known to be in Latin-1 or UTF-8: it is not used to re-encode the input.

**Comment by gitzhuoer** [comment]
```
options(encoding = "UTF-8")

foobar <- function(str) {
  print(str)
  print(Encoding(str))
  print(charToRaw(str))
}
```

```
foobar(readLines('test.yml'))
```
```
[1] "章"
[1] "unknown"
[1] d5 c2
```

```
foobar(readLines('test.yml', encoding = 'UTF-8'))
```
```
[1] "\xd5\xc2"
[1] "UTF-8"
[1] d5 c2
```

```
foobar(readLines(file('test.yml', encoding = 'UTF-8')))
```
```
[1] "章"
[1] "UTF-8"
[1] e7 ab a0
```

```
foobar(readLines(file('test.yml', encoding = 'UTF-8'), encoding = 'UTF-8'))
```
```
[1] "章"
[1] "UTF-8"
[1] e7 ab a0
```

**Comment by viking** [comment]
Aha, I believe I understand what you're saying. Thanks for delving into this.

**Comment by viking** [comment]
I have merged in your pull request (https://github.com/viking/r-yaml/pull/40). Thanks again.
