### ISSUE TITLE
List of lists with one element not parsed correctly

### ISSUE THREAD

**Issue by b-dawes** [viking/r-yaml#45]
If you have a list which only contains one list, this is returned as a string containing an R expression.

For example:
```
x <- 'a:\n -\n  - b\n  - c\n'
yaml.load(x)
```
returns:
```
$a
[1] "c(\"b\", \"c\")"
```

If a second list is added to the larger list, things work as expected.
```
y <- 'a:\n -\n  - b\n  - c\n -\n  - d\n'
yaml.load(y)
```
returns:
```
$a
$a[[1]]
[1] "b" "c"

$a[[2]]
[1] "d"
```

**Comment by viking** [comment]
Interesting! I'll check it out.

**Comment by viking** [comment]
Thanks for your report.
