### ISSUE TITLE
data dictionary specification to dataframe doesn't work

### ISSUE THREAD

**Issue by shadiakiki1986** [viking/r-yaml#50]
Hello. Thanks for this awesome package.

Trying out the `yaml.load` on the data dictionary specification example on the repository's front page:
```
> data.frame(yaml.load("- field: ID
+   description: primary identifier
+   type: integer
+   primary key: yes
+ - field: DOB
+   description: date of birth
+   type: date
+   format: yyyy-mm-dd
+ - field: State
+   description: state of residence
+   type: string"))
```
yields
```
  field        description    type primary.key field.1 description.1 type.1
1    ID primary identifier integer        TRUE     DOB date of birth   date
      format field.2      description.2 type.2
1 yyyy-mm-dd   State state of residence string
```
with only 1 row instead of 3 rows

**Comment by shadiakiki1986** [comment]
actually, I figured out a workaround with the help of [SO](https://stackoverflow.com/questions/29674661/r-list-of-lists-to-data-frame#comment47486926_29674661), but it only works if the *same* columns are present

```
x = yaml.load("
- field: ID
  description: primary identifier
  type: integer
  primary key: yes
- field: DOB
  description: date of birth
  type: date
  primary key: yes
- field: State
  description: state of residence
  type: date
  primary key: yes
")
data.frame(do.call(rbind, x))
```

**Comment by viking** [comment]
You're right, the data dictionary example would not be converted into a data frame by the `yaml` package. It's not really meant to be a data frame, it's mostly there as an example for what YAML looks like (as it's under the "What is YAML?" heading). There is more information about converting `data.frame` objects further down into the documentation.

Thanks for your interest in the `yaml` package!

**Comment by viking** [comment]
If you have any further comments about this let me know.
