### ISSUE TITLE
Bad YAML is generated for string with many spaces

### ISSUE THREAD

**Issue by rikardn** [viking/r-yaml#51]
I run the following command using the yaml package version 2.1.16:
`as.yaml(list(command_line="ab ab ab ab ba fd fdg dfg w rfwf sf sf sf sd fs fs fsd fsd fsd fsd fs r"))`

The result I get:
`"command_line: ab ab ab ab ba fd fdg dfg w rfwf sf sf sf sd fs fs fsd fsd fsd fsd fs\n  r\n"`

The result has an extra line break which shouldn't be there. The resulting string is not correct YAML.

**Comment by viking** [comment]
This is actually valid. Try this:

```r
x <- list(command_line="ab ab ab ab ba fd fdg dfg w rfwf sf sf sf sd fs fs fsd fsd fsd fsd fs r")
y <- as.yaml(x)
z <- yaml.load(y)
all.equal(x, z)
```

**Comment by viking** [comment]
From the YAML specification (http://yaml.org/spec/1.1/):

> Motivated by HTML’s end-of-line normalization, YAML’s line folding employs an intuitive method of handling line breaks. A single line break is folded into a single space, while empty lines are interpreted as line break characters. This technique allows for paragraphs to be word-wrapped without affecting the canonical form of the content.

**Comment by rikardn** [comment]
Ah, you are right! It is perfectly valid. Thanks for the good explanation.

I also tested it in python with
```
import yaml
yaml.load(open('test.yaml'))
```

which gives
`{'command_line': 'ab ab ab ab ba fd fdg dfg w rfwf sf sf sf sd fs fs fsd fsd fsd fsd fs r'}`
