### ISSUE TITLE
Expressions always evaluated in global environment

### ISSUE THREAD

**Issue by christianhomberg** [viking/r-yaml#54]
Minimum example:
```
foo_fun1 = function() {
  foo = "foo"
  yaml::yaml.load("!expr print(foo)")
}

# will throw error
foo_fun1()

foo_fun2 = function() {
  foo <<- "foo"
  yaml::yaml.load("!expr print(foo)")
}

# will print "foo"
foo_fun2()
rm(list=ls())
```

As you can see, expressions are evaluated in the global environment which is why `foo_fun2` runs and `foo_fun1` doesn't.

This is unexpected (to me) because if anything I'd expect both (i.e. both functions inherit from parents) or neither (i.e. `yaml.load` runs in new environment that doesn't inherit from any environments) functions to work.

**Comment by viking** [comment]
Yes, it always executes in the global environment. See the call [here](https://github.com/viking/r-yaml/blob/e7010459840de6c59b8d0a6dcd32dda39e2ddf23/src/r_parse.c#L370). You can override the default `!expr` handler and it will work like you want:

```r
foo_fun1 = function() {
  foo = "foo"
  yaml::yaml.load("!expr print(foo)", handlers = list(expr = function(str) eval(parse(text=str))))
}
foo_fun1()
```

I'm hesitant to change the behavior for the default handler. Evaluating expressions in a YAML document was not really meant to be used as a way to process local variables. Additionally, evaluating expressions is being turned off by default soon for safety reasons (see https://github.com/viking/r-yaml/issues/47).

For evaluating local variables I think the better way is to use a templating package like [brew](https://cran.r-project.org/web/packages/brew/) or [whisker](https://cran.r-project.org/web/packages/whisker/). This pattern is common in languages like Ruby.

**Comment by christianhomberg** [comment]
Thanks for the quick reply, that does the trick.

**Comment by yihui** [comment]
I think it will be nice if users can pass a custom environment to `yaml.load()` to evaluate the expressions (e.g., the signature could be `yaml.load = function(..., envir = parent.frame())`), but I completely understand that the developer of **yaml** is not interested in this idea. And thanks for the trick!

**Comment by spgarbet** [comment]
@yihui I'm confused, is this a new request? Why wouldn't I be interested?

**Comment by yihui** [comment]
@spgarbet Sorry about the confusion! I was replying to @viking above (by "developer" I actually meant him, the original developer).

Anyway, I'm happy to use the trick mentioned above, so I don't have a new request. Thank you!
