### ISSUE TITLE
Use of Merge Keys

### ISSUE THREAD

**Issue by bsaul** [viking/r-yaml#58]
I'm trying to using merge keys to modify a template. For example, I have the following YAML:
```
---
aliases :
- &template
  name  : replace_me
  label : "Here's to hoping that replace_me is replaced"

variables:
- *template
- <<: *template
  name: test
```
When I run `read_yaml`, I get a list with 2 variables items as I expect, but the second variable has two names: "replace_me" and "test":

![image](https://user-images.githubusercontent.com/4882990/41053804-97b37f02-698a-11e8-8356-4abc7a194f0b.png)

I think I have correct YAML syntax for a merge. Are merge keys supported by the `yaml` package? I couldn't find evidence that `yaml` or `LibYAML` don't support merge keys.

Thanks!

**Comment by viking** [comment]
Merge keys are supported in this package, but you may have found a bug. I'll check it out.

**Comment by viking** [comment]
It's a bug that there are two name keys. However, the expected behavior of your example is that the value "test" is ignored for the "name" key. See the specification here: http://yaml.org/type/merge.html. You would need to do this:
```yaml
variables:
- *template
- name: test
  <<: *template
```

I'll work on fixing the duplicate key issue.

**Comment by bsaul** [comment]
Got it. Thanks!

**Comment by viking** [comment]
This should be fixed now. It gives a warning when a key is ignored, but I may do away with that. You can give it a shot by installing the package from Github: https://github.com/viking/r-yaml#git-via-devtools
