### ISSUE TITLE
boolean encoding in as.yaml()

### ISSUE THREAD

**Issue by dselivanov** [viking/r-yaml#59]
Hi here. First of all thank for a great package.

According to the source code in the repo I see that logical values are always encoded as `yes`/`no`. Is it possible to make it configurable (without regeneration of C code)?

**Comment by viking** [comment]
Yeah, I've been planning (for a while) to work on this as well as controlling how other types are converted to YAML. The first request for this specific feature was made in issue #30. I will get to it eventually when I can, possibly in the next release or two.

**Comment by dselivanov** [comment]
sorry I missed that. Closing in favor of #30

**Comment by viking** [comment]
No worries.
