### ISSUE TITLE
utf-8 encoding after yaml.load_file

### ISSUE THREAD

**Issue by HenricoWitvliet** [viking/r-yaml#6]
I've got a file with utf-8 characters. yaml.load_file loads the character strings correctly. But the encoding, as given by Encoding(), returns unknown. Now I use Encoding(...) <-'UTF-8' to set the encoding.
It would be nice if the character strings had the utf-8 encoding bit set.

**Comment by yihui** [comment]
We just ran into the same problem. It will be nice if you can explicitly mark the encoding of character strings as UTF-8. Thanks! (We probably do not need to worry about UTF-16)

**Comment by viking** [comment]
I had forgotten about this issue, unfortunately. I will take a fresh look at it.

**Comment by yihui** [comment]
Thanks! FWIW, this is our current workaround: https://github.com/rstudio/rmarkdown/pull/421/files (Recursively mark the character elements of `yaml.load()` output as UTF-8)

**Comment by ofurkusi** [comment]
There seem to be two issues here, one with ``yaml.load_file`` and another with ``yaml.load``.

When ``yaml.load_file`` calls ``readLines`` without explicitly defining the encoding as UTF-8,  the contents of a valid UTF-8 encoded yaml file is read into a string with the encoding set to *unknown* (while in fact being UTF-8). On Windows, R treats the string as latin1 (I guess) so the characters are all garbled when displayed. By adding ``encoding="UTF-8`` as a parameter to ``readLines`` the raw text input is read correctly and set as UTF-8 before being passed on to ``readLines``.

While I suggest setting ``encoding="UTF-8`` parameter for ``readLines`` in ``yaml.load_file`` it does not seem to be enough to fix the problem. Once ``yaml.load`` starts processing the text read by ``readLines``, it messes the characters up again by reverting the encoding to ``unknown``.

**Comment by yihui** [comment]
We were bitten by this issue again: https://github.com/rstudio/bookdown/issues/142 Is there a chance that you could fix it? The fix should be fairly simple (mark the input and output strings as UTF-8), and I'm just not familiar with C.

**Comment by shrektan** [comment]
We encountered the same issue as well, although it can by solved as @yihui did in https://github.com/rstudio/bookdown/blob/3ed7fc6bd30e2832948d28298dee5cd546339fc8/R/utils.R#L82 

We thought it would be nicer if it's fixed in the package `yaml`.

Thanks.

**Comment by yihui** [comment]
And bitten by this again https://github.com/rstudio/rmarkdown/pull/841 so yet yet another patch...

**Comment by viking** [comment]
Unfortunately I have precious little time to work on this project at present. A pull request would be appreciated.

**Comment by yihui** [comment]
@viking Okay, actually that is all I need from you. I'll try to find someone to do the work and submit a pull request. Thanks!

**Comment by yihui** [comment]
@viking Done in #32. Tested on Windows and \*nix.

In the long run, if you feel it is difficult for you to maintain this package, you may consider finding a new maintainer. It seems you are having the similar situation of the [**tikzDevice**](https://github.com/yihui/tikzDevice) package, which is a package that I was highly interested in but the original authors lacked time. The **yaml** package is critical to the R Markdown world, and I hope you could consider [increasing the bus factor](https://en.wikipedia.org/wiki/Bus_factor#Increasing_the_bus_factor) so this important project can be carried forward nicely in the future.

BTW, I found this article very inspiring: [I gave commit rights to someone I didn't know, I could never have guessed what happened next!](http://jakewins.com/p/clickbait).

**Comment by viking** [comment]
Thank you.

**Comment by yihui** [comment]
@viking Any chance you could make a CRAN release soon? I hate bugging you like this, but without the CRAN release, we just keep hearing users report this issue. Here again: http://rmarkdown.rstudio.com/r_notebooks.html#comment-2982649887

**Comment by viking** [comment]
I'll get to it soon. Not being funded to do this means that I have other priorities. Please recognize that.

**Comment by viking** [comment]
I don't wish to continue this discussion here. I will let you know when the new version is on CRAN.

**Comment by yihui** [comment]
Yep definitely understood, and much appreciated!

**Comment by viking** [comment]
New version is up on CRAN as of about 10 minutes ago.
