### ISSUE TITLE
Unquoted y in yaml yields TRUE in R

### ISSUE THREAD

**Issue by bsaul** [viking/r-yaml#61]
This is an odd bug. With the following yaml:

```
x1: z
x2: "y"
x3: y
x4: y
```

`read_yaml` returns:

```
$x1
[1] "z"

$x2
[1] "y"

$x3
[1] TRUE

$x4
[1] TRUE
```

I've played with other letters, but `y` always seems to return `TRUE` unless it is quoted in the yaml.

**Comment by viking** [comment]
Check out the replies to issue #5. The YAML specification actually specifies that unquoted y and n are boolean.
