### ISSUE TITLE
mingw_64 issuing lots of warnings for unused variables on installation

### ISSUE THREAD

**Issue by ScientificProgrammer** [viking/r-yaml#63]
## Summary of Issue

I'm using RTools on Win 10. I've been having problems while using RStudio to create RMarkdown documents, which I believe are due to a problem with my installation of the 
yaml package. I reinstalled it, which seemed to fix the problems I was observing (*e.g.* yaml configuration options being ignored). However, the large number of compiler warnings do concern me. Is this behavior normal, or is their likely something else wrong with my configuration?

## Output from installing yaml

    > devtools::install_github("viking/r-yaml")
    Downloading GitHub repo viking/r-yaml@master
    from URL https://api.github.com/repos/viking/r-yaml/tarball/master
    Installing yaml
    Running "C:/R/R-3.5.1/bin/x64/Rcmd.exe" INSTALL \
      "C:/temp/RtmpaWzbqp/devtools59c7a666c2c/viking-r-yaml-aba5d96" \
      "--library=C:/R/R-3.5.1/library" --install-tests 
    * installing *source* package 'yaml' ...

    ** libs

    *** arch - i386

    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c api.c -o api.o
    api.c: In function 'yaml_document_delete':

    api.c:1133:7: warning: variable 'context' set but not used [-Wunused-but-set-variable]

         } context;

           ^

    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c dumper.c -o dumper.o
    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c emitter.c -o emitter.o
    emitter.c: In function 'yaml_emitter_write_plain_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:1933:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    emitter.c: In function 'yaml_emitter_write_single_quoted_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:1994:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    emitter.c: In function 'yaml_emitter_write_literal_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:2257:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    emitter.c: In function 'yaml_emitter_write_folded_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:2306:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c implicit.c -o implicit.o
    implicit.re: In function 'Ryaml_find_implicit_tag':

    implicit.re:12:24: warning: variable 'limit' set but not used [-Wunused-but-set-variable]

       const char *cursor, *limit, *marker;

                            ^

    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c loader.c -o loader.o
    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c parser.c -o parser.o
    parser.c: In function 'yaml_parser_parse_block_sequence_entry':

    parser.c:762:21: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

             yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                         ^

    parser.c: In function 'yaml_parser_parse_block_mapping_key':

    parser.c:872:21: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

             yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                         ^

    parser.c: In function 'yaml_parser_parse_flow_sequence_entry':

    parser.c:955:17: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

         yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                     ^

    parser.c: In function 'yaml_parser_parse_flow_mapping_key':

    parser.c:1107:17: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

         yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                     ^

    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c r_emit.c -o r_emit.o
    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c r_ext.c -o r_ext.o
    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c r_parse.c -o r_parse.o
    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c reader.c -o reader.o
    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c scanner.c -o scanner.o
    scanner.c: In function 'yaml_parser_decrease_flow_level':

    scanner.c:1189:23: warning: variable 'dummy_key' set but not used [-Wunused-but-set-variable]

         yaml_simple_key_t dummy_key;    /* Used to eliminate a compiler warning. */

                           ^

    c:/Rtools/mingw_32/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O3 -Wall  -std=gnu99 -mtune=generic -c writer.c -o writer.o
    c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o yaml.dll tmp.def api.o dumper.o emitter.o implicit.o loader.o parser.o r_emit.o r_ext.o r_parse.o reader.o scanner.o writer.o -LC:\Rtools\local323/lib/i386 -LC:\Rtools\local323/lib -LC:/R/R-3.5.1/bin/i386 -lR
    installing to C:/R/R-3.5.1/library/yaml/libs/i386

    *** arch - x64

    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c api.c -o api.o
    api.c: In function 'yaml_document_delete':

    api.c:1133:7: warning: variable 'context' set but not used [-Wunused-but-set-variable]

         } context;

           ^

    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c dumper.c -o dumper.o
    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c emitter.c -o emitter.o
    emitter.c: In function 'yaml_emitter_write_plain_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:1933:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    emitter.c: In function 'yaml_emitter_write_single_quoted_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:1994:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    emitter.c: In function 'yaml_emitter_write_literal_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:2257:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    emitter.c: In function 'yaml_emitter_write_folded_scalar':

    emitter.c:28:6: warning: value computed is not used [-Wunused-value]

          && ((emitter->line_break == YAML_CR_BREAK ?                                \

          ^

    emitter.c:56:11: note: in expansion of macro 'PUT_BREAK'

              (PUT_BREAK(emitter),                                                   \

               ^

    emitter.c:2306:18: note: in expansion of macro 'WRITE_BREAK'

                 if (!WRITE_BREAK(emitter, string)) return 0;

                      ^

    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c implicit.c -o implicit.o
    implicit.re: In function 'Ryaml_find_implicit_tag':

    implicit.re:12:24: warning: variable 'limit' set but not used [-Wunused-but-set-variable]

       const char *cursor, *limit, *marker;

                            ^

    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c loader.c -o loader.o
    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c parser.c -o parser.o
    parser.c: In function 'yaml_parser_parse_block_sequence_entry':

    parser.c:762:21: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

             yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                         ^

    parser.c: In function 'yaml_parser_parse_block_mapping_key':

    parser.c:872:21: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

             yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                         ^

    parser.c: In function 'yaml_parser_parse_flow_sequence_entry':

    parser.c:955:17: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

         yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                     ^

    parser.c: In function 'yaml_parser_parse_flow_mapping_key':

    parser.c:1107:17: warning: variable 'dummy_mark' set but not used [-Wunused-but-set-variable]

         yaml_mark_t dummy_mark;     /* Used to eliminate a compiler warning. */

                     ^

    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c r_emit.c -o r_emit.o
    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c r_ext.c -o r_ext.o
    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c r_parse.c -o r_parse.o
    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c reader.c -o reader.o
    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c scanner.c -o scanner.o
    scanner.c: In function 'yaml_parser_decrease_flow_level':

    scanner.c:1189:23: warning: variable 'dummy_key' set but not used [-Wunused-but-set-variable]

         yaml_simple_key_t dummy_key;    /* Used to eliminate a compiler warning. */

                           ^

    c:/Rtools/mingw_64/bin/gcc  -I"C:/R/R-3.5.1/include" -DNDEBUG -I. -DNDEBUG    -I"C:\Rtools\local323/include"     -O2 -Wall  -std=gnu99 -mtune=generic -c writer.c -o writer.o
    c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o yaml.dll tmp.def api.o dumper.o emitter.o implicit.o loader.o parser.o r_emit.o r_ext.o r_parse.o reader.o scanner.o writer.o -LC:\Rtools\local323/lib/x64 -LC:\Rtools\local323/lib -LC:/R/R-3.5.1/bin/x64 -lR
    installing to C:/R/R-3.5.1/library/yaml/libs/x64

    ** R

    ** inst

    ** tests

    ** byte-compile and prepare package for lazy loading

    ** help

    *** installing help indices

      converting help for package     finding HTML links ...'yaml'

     done

        as.yaml                                 html  

        read_yaml                               html  

        write_yaml                              html  

        yaml.load                               html  

    ** building package indices

    ** testing if installed package can be loaded

    *** arch - i386

    *** arch - x64

    * DONE (yaml)

    Making 'packages.html' ... done

    In R CMD INSTALL

    >

**Comment by viking** [comment]
These warnings are normal. Compilers may be more verbose due to default settings, and it appears that mingw compilers have stricter warnings enabled. The libyaml code is built as part of this package, and that code has some unused variables. These variables are causing the warnings.

I don't patch libyaml unless I have a very good reason though, so I haven't fixed the warnings. However, when future versions of libyaml are released, these warnings may go away when the new libyaml version is incorporated in the yaml R package.

**Comment by ScientificProgrammer** [comment]
Thank you for taking the time to respond. I fully understand your rationale! Also, thanks for contributing this great package to the R community!
