### ISSUE TITLE
no quote for special character

### ISSUE THREAD

**Issue by hubentu** [viking/r-yaml#64]
@viking The function "as.yaml" return special character with single quote. Is there a way to remove the quote? Thanks!
```
> cat(as.yaml("[]"))
'[]'
```

**Comment by viking** [comment]
You're attempting to convert a string (`"[]"`) to YAML. The `as.yaml` function will quote strings that could be interpreted as something else. In your case, `[]` would be treated as an empty sequence. If you want to convert a real empty sequence, you can do this: `as.yaml(list())`

Does that answer your question?

**Comment by hubentu** [comment]
Thanks for quick reply. I need to convert a string with ``"[]"``, not a empty one, such as ``"[abc]"``. Any solution? Thanks again.

**Comment by hubentu** [comment]
I am trying to write a workflow file using Common Workflow Language. In the ``out`` section, a value with "[]" (``[example_out]``) connect the output value to downstream parameters. 
http://www.commonwl.org/user_guide/21-1st-workflow/

Two ways work in my test:
```
out: [example_out]
```
```
out:
- example_out
```
These didn't works.
```
out: '[example_out]'
```
or
```
out: example_out
```
Thanks!

**Comment by viking** [comment]
Ah, I see. So it seems there's a custom language called CWL that looks very much like YAML, but there are some differences.

I'm afraid that the R yaml package won't be able to do what you want without some postprocessing on your part. You could do something like this:

```r
x <- 'abc'
class(x) <- 'cwl_out'
y <- list(foo = 'bar', out = x)
result <- as.yaml(y, handlers = list(cwl_out = function(s) paste0('__cwlout__', s, '__cwlout__')))
result <- gsub("__cwlout__(.+?)__cwlout__", "[\\1]", result)
```

The result of this would be:

```yaml
foo: bar
out: [abc]
```

**Comment by viking** [comment]
It's worth nothing that the above code will only work with the yaml package version 2.2.0 and greater. The `handlers` argument to `as.yaml` was only recently added.

**Comment by viking** [comment]
This will also work, given you example above:

```r
as.yaml(list(foo = 'bar', out = list('abc')))
```

The result of that is:
```yaml
foo: bar
out:
- abc
```

**Comment by hubentu** [comment]
I used your ``write_yaml`` to convert, so I have to read it back, modify and write it out.
Your second solution is great! Just a ``list``. Thanks!
