### ISSUE TITLE
Support for type specification?

### ISSUE THREAD

**Issue by LukeGoodsell** [viking/r-yaml#66]
Is it possible to parse objects with [yaml bool type specifications](http://yaml.org/type/bool.html)? E.g.:

```r
> yaml::yaml.load("myObject: !!bool 'true'")
$myObject
[1] "true"
```

I would expect this to be parsed as a logical object, instead of a string.

**Comment by viking** [comment]
Yep, you're right. It's a bug.

The reason it doesn't work is because of how types are implicitly discovered. Boolean values like "true" are internally typed as "bool#yes", likewise "false" is "bool#no". The type "bool" is not being handled at all, currently. It shouldn't be too difficult to fix.

**Comment by viking** [comment]
However, I need to consider how this is handled in other implementations. Ruby doesn't handle this properly either:

```
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> YAML.parse("myObject: !!bool 'true'")
=> #<Psych::Nodes::Document:0x000055afaf6e0370 @children=[#<Psych::Nodes::Mapping:0x000055afaf6e02f8 @children=[#<Psych::Nodes::Scalar:0x000055afaf6e0258 @value="myObject", @anchor=nil, @tag=nil, @plain=true, @quoted=false, @style=1, @start_line=0, @start_column=0, @end_line=0, @end_column=8>, #<Psych::Nodes::Scalar:0x000055afaf6e01e0 @value="true", @anchor=nil, @tag="tag:yaml.org,2002:bool", @plain=false, @quoted=false, @style=2, @start_line=0, @start_column=10, @end_line=0, @end_column=23>], @anchor=nil, @tag=nil, @implicit=true, @style=1, @start_line=0, @start_column=0, @end_line=1, @end_column=0>], @version=[], @tag_directives=[], @implicit=true, @implicit_end=true>
irb(main):003:0> 
```

**Comment by viking** [comment]
I checked Ruby and Python implementations, and they behave as you expect. I deleted a comment about Ruby's implementation behaving incorrectly (you may have been e-mailed), but I was mistaken.

**Comment by viking** [comment]
Thanks for the report. This should be fixed in master now.

**Comment by LukeGoodsell** [comment]
Great. Thanks for the fast turn-around!
