### ISSUE TITLE
Keys read a boolean

### ISSUE THREAD

**Issue by jkh1** [viking/r-yaml#71]
I know that the YAML specification says that unquoted Y/N/F/T should be read as boolean and I am aware of the other issues mentioning this (e.g. #24, #5). However the r-yaml package docs says (for the yaml.load() function) that "... all the keys in the map are converted to strings." which I think is a broken promise when the key is Y/N/F/T.

**Comment by viking** [comment]
The key actually is a string. Consider:

```r
x <- yaml.load("yes: foo")
print(x)
# $`TRUE`
# [1] "foo"
class(names(x)) #=> "character"
```

If you want the key to be `"yes"`, then you need to add a custom handler as has been described elsewhere.

**Comment by jkh1** [comment]
So Y/N/T/F are read as booleans which are then converted to strings. Indeed this conforms to the docs. It's a gotcha to be aware of.
