### ISSUE TITLE
write_yaml file should default to stdout

### ISSUE THREAD

**Issue by MichaelChirico** [viking/r-yaml#73]
I think it's kind of standard (?) for R writing facilities to default to writing to `stdout`. Certainly true for `writeLines` and `write.table`/`write.csv` and we've done it for `fwrite`:

```
x = letters[1:3]
writeLines(x)
# a
# b
# c
write.table(x)
# "x"
# "1" "a"
# "2" "b"
# "3" "c"
write.csv(x)
# "","x"
# "1","a"
# "2","b"
# "3","c"
data.table::fwrite(list(x))
# a
# b
# c
```

So it's unfortunate `write_yaml` doesn't do the same:

```
write_yaml(x)
```

> Error in `write_yaml(x)` : argument `file` is missing, with no default

But of course `write_yaml` does support file connections so the fix would be easy:

```
write_yaml(x, stdout())
# - a
# - b
# - c
```

Happy to file a PR.

**Comment by viking** [comment]
The `write_yaml` function was written in the style of [readr](https://readr.tidyverse.org/) functions. It is indeed unfortunate that there is a confusing similarity with `writeLines`. However, the intention of `write_yaml` was to mimic the readr functions.

**Comment by viking** [comment]
Let me know if you have any further questions/comments, but this doesn't seem like a bug to me so I'll close the issue.
