### ISSUE TITLE
String 'NO' is incorrectly converted to 'FALSE'

### ISSUE THREAD

**Issue by vz-x** [viking/r-yaml#93]
Sample code:

`yaml::read_yaml(text = c('NO: Norway', 'FI: Finland', 'GB: United Kingdom'))`

Actual output:
$'FALSE'
[1] "Norway"

$FI
[1] "Finland"

$GB
[1] "United Kingdom"

Expected output:
$NO
[1] "Norway"

$FI
[1] "Finland"

$GB
[1] "United Kingdom"

**Comment by malcolmbarrett** [comment]
`no` and `false` mean the same thing in YAML. You need to quote the letters NO to get a literal "no":

``` r
yaml::read_yaml(text = c('"NO": Norway', 'FI: Finland', 'GB: United Kingdom'))
#> $NO
#> [1] "Norway"
#> 
#> $FI
#> [1] "Finland"
#> 
#> $GB
#> [1] "United Kingdom"
```

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by spgarbet** [comment]
Check this related issue out: https://github.com/viking/r-yaml/issues/5

**Comment by vz-x** [comment]
Some other YAML validators are not agree with you ;-)
https://yamlvalidator.com/

**Comment by malcolmbarrett** [comment]
https://yaml.org/type/bool.html

**Comment by vz-x** [comment]
What do you think about extra parameter for yaml::yaml.load function to completely disable bool type recognition? That will clearly against YAML specification, but may be useful in a lot of practical cases.

**Comment by spgarbet** [comment]
Did you read the thread on #5? One can write their own type handlers and make it as non-compliant as you desire.

**Comment by viking** [comment]
As others have mentioned, the answer to this can be found in the discussion for #5. Let me know if you have any additional questions.
