### ISSUE TITLE
Strings containing only digits with starting '0' incorrectly treated as integers

### ISSUE THREAD

**Issue by vz-x** [viking/r-yaml#94]
According YAML specification only numbers staring with 1-9 or '-' are integers or floats, Strings staring from '0' must be treated as strings.

**Comment by spgarbet** [comment]
Which specification 1.1 or 1.2?

**Comment by vz-x** [comment]
1.2
Is r-yaml  locked to 1.1 version of YAML?

**Comment by malcolmbarrett** [comment]
https://github.com/viking/r-yaml/issues/76

**Comment by viking** [comment]
See https://yaml.org/type/int.html. A leading '0' indicates an octal number. As others have mentioned, this package currently supports YAML version 1.1. Let me know if you have any additional questions.

**Comment by cderv** [comment]
> A leading '0' indicates an octal number. As others have mentioned, this package currently supports YAML version 1.1. Let me know if you have any additional questions.

How to write from R the correct YAML so that it is a string? 

``` r
yaml::as.yaml(list(number = "029"))
#> [1] "number: 029\n"
```

``` r
yaml::as.yaml(list(number = "'029'"))
#> [1] "number: '''029'''\n"
yaml::yaml.load(yaml::as.yaml(list(number = "'029'")))
#> $number
#> [1] "'029'"
```

I can't find the right way to write the string '029' to YAML file to have it parsed correctly. 🤔 

Maybe because it is parsed the same ? 
``` r
yaml::yaml.load("number: 029")
#> $number
#> [1] "029"
yaml::yaml.load("number: '029'")
#> $number
#> [1] "029"
```

so roundtrip is not possible... 
``` r
yaml::as.yaml(yaml::yaml.load("number: '029'"))
#> [1] "number: 029\n"
```

thanks for your help

**Comment by cderv** [comment]
Sorry - I should have read code and doc more carefully. This is about the attribute tricks. 

``` r
x <- "029"
attr(x, "quoted") <- TRUE
yaml::as.yaml(list(number = x))
#> [1] "number: \"029\"\n"
```
