### ISSUE TITLE
reading/writing Ns

### ISSUE THREAD

**Issue by robmaz** [viking/r-yaml#96]
It looks like an unquoted N character is unconditionally read as the logical value FALSE. When writing, it is therefore quoted.
Is this really how it should be? I get it that a list that only has Y and N entries could be converted to a logical vector
for convenience, but if there are more than these two letters, it does not seem to make too much sense. 

Example:

alphabet: [A, C, G, T, N]

does not what at least I would have expected. When writing, one gets

alphabet: [A, C, G, T, 'N']

which looks also a bit weird.

**Comment by spgarbet** [comment]
Check out Issue #5. 

This is an oddity of YAML 1.1. This library was built around libyaml which has not upgraded to 1.2.

**Comment by robmaz** [comment]
Apparently a duplicate of #5
